MadwaysKommunalomatBundleQuestion:
    pattern: /question/{weight}
    defaults: { _controller: MadwaysKommunalomatBundle:Question:index, weight: 1 }
    requirements:
        weight:  \d+

MadwaysKommunalomatBundleQuestionAdd:
    pattern: /admin/question/add
    defaults: { _controller: MadwaysKommunalomatBundle:Question:create, weight: 1 }
    requirements:
        weight:  \d+

MadwaysKommunalomatBundleAdminOverview:
    pattern:  /admin
    defaults: 
        _controller: FrameworkBundle:Template:template
        template:    'MadwaysKommunalomatBundle::admin.html.twig'