MadwaysKommunalomatBundleQuestionAnswer:
    pattern: /question/{weight}
    defaults: { _controller: MadwaysKommunalomatBundle:Question:answer, weight: 1 }
    requirements:
        weight:  \d+

MadwaysKommunalomatBundleResult:
    pattern: /result/{id}
    defaults: { _controller: MadwaysKommunalomatBundle:Question:result, id: null }
    requirements:
        id:  \d+

MadwaysKommunalomatBundleQuestion:
    pattern: /admin/question
    defaults: { _controller: MadwaysKommunalomatBundle:Question:index }

MadwaysKommunalomatBundleQuestionCreate:
    pattern: /admin/question/create
    defaults: { _controller: MadwaysKommunalomatBundle:Question:form }

MadwaysKommunalomatBundleQuestionEdit:
    pattern: /admin/question/{id}
    defaults: { _controller: MadwaysKommunalomatBundle:Question:form }
    requirements:
        id:  \d+

MadwaysKommunalomatBundleQuestionDelete:
    pattern: /admin/question/{id}/delete
    defaults: { _controller: MadwaysKommunalomatBundle:Question:delete }
    requirements:
        id:  \d+

MadwaysKommunalomatBundleQuestionMove:
    pattern: /admin/question/{id}/move/{direction}
    defaults: { _controller: MadwaysKommunalomatBundle:Question:move }
    requirements:
        id:  \d+
        direction: up|down

MadwaysKommunalomatBundleParty:
    pattern: /admin/party
    defaults: { _controller: MadwaysKommunalomatBundle:Party:index }

MadwaysKommunalomatBundlePartyCreate:
    pattern: /admin/party/create
    defaults: { _controller: MadwaysKommunalomatBundle:Party:form }

MadwaysKommunalomatBundlePartyEdit:
    pattern: /admin/party/{id}
    defaults: { _controller: MadwaysKommunalomatBundle:Party:form }
    requirements:
        id:  \d+

MadwaysKommunalomatBundlePartyDelete:
    pattern: /admin/party/{id}/delete
    defaults: { _controller: MadwaysKommunalomatBundle:Party:delete }
    requirements:
        id:  \d+

MadwaysKommunalomatBundlePartyAnswer:
    pattern: /admin/party/{id}/answer
    defaults: { _controller: MadwaysKommunalomatBundle:Party:answer }
    requirements:
        id:  \d+

MadwaysKommunalomatBundleAdminOverview:
    pattern:  /admin
    defaults: 
        _controller: FrameworkBundle:Template:template
        template:    'MadwaysKommunalomatBundle::admin.html.twig'
