parameters:
#    madways_kommunalomat.example.class: Madways\KommunalomatBundle\Example

services:
  twig.extension.txt:
      class: Twig_Extensions_Extension_Text
      tags:
        - { name: twig.extension }

